stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: gardashaliyeva/devops_task2
  IMAGE_TAG: node_1

test:
  image: node:16-alpine
  stage: test
  script:
    - npm install
    - npm test

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_PRIVATE_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY win11@172.22.160.1 "
        docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD &&
        docker ps -aq | xargs docker stop | xargs docker rm &&
        docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG"
  only:
    - main