stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: gardashaliyeva/devops_task2
  IMAGE_TAG: node_1

test:
  image: node:16-alpine
  stage: test
  script:
    - npm install
    - npm test

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  image: docker:latest
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apk add --update openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - ssh win11@127.0.0.1 "docker pull $IMAGE_NAME:$IMAGE_TAG && docker stop web-app || true && docker rm web-app || true"
    - ssh win11"@127.0.0.1 "docker run -d --name web-app -p 80:3000 $IMAGE_NAME:$IMAGE_TAG"
  only:
    - main



