stages:
  - build
  - test
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

test:
  stage: test
  script:
    - docker pull $IMAGE_TAG
    - docker run --name web-app-test -d $IMAGE_TAG
    - docker exec web-app-test npm test
    - docker stop web-app-test
    - docker rm web-app-test

deploy:
  stage: deploy
  script:
    - docker pull $IMAGE_TAG
    - docker stack deploy --with-registry-auth -c docker-compose.yml web-app
  only:
    - develop
