stages:
  - test
  - build

variables:
  IMAGE_NAME: registry.gitlab.com/gardashaliyeva/devops_task2
  IMAGE_TAG: node_1

test:
  image: node:16-alpine
  stage: test
  script:
    - npm install
    - npm test

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG


