version: '3.8'

services:
  web-app:
    image: Gardashaliyeva/DevOps_task2:node_1
    ports:
      - "80:3000"
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      NODE_ENV: production
    networks:
      - webnet

networks:
  webnet:
